print("Hi, everyone!")
print("My name is Wildan Hafidz Mauludin. I'm from Mini Class WEB")
print("I'm interested about Startup")
print("I also love to learn a new languages, hiking, and do some physical activites bcs it moves my body and makes me feel more healthy")
print("If we have the same interest or hobbies, please hit me up on my LinkedIn")
print("Pleasure to meet you guys!")
